// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlOnWT2Rpdl3cQs2iaCGwClSJklV2dj2U',
    appId: '1:382899224834:android:419efd80988cd87277421b',
    messagingSenderId: '382899224834',
    projectId: 'renth-2ddf9',
    storageBucket: 'renth-2ddf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG99Z0u73VV65fB0fyVnnyRrrgio1127g',
    appId: '1:382899224834:ios:f45bf42ad7e9d95177421b',
    messagingSenderId: '382899224834',
    projectId: 'renth-2ddf9',
    storageBucket: 'renth-2ddf9.firebasestorage.app',
    androidClientId: '382899224834-049e385pam8dj8gk8sra4cbg5veelrj3.apps.googleusercontent.com',
    iosClientId: '382899224834-lds943auad9qpnuqehi7lb8si2j268f7.apps.googleusercontent.com',
    iosBundleId: 'com.quicktech.renthManager',
  );
}
